# Data parameters
data:
  datadir: 'data'
  xtrain_path: 'BLR_X_normalized.csv'
  ytrain_path: 'BLR_Y.csv'
  xval_path: 'DEL_X_normalized.csv'
  yval_path: 'DEL_Y.csv'
  xpred_path: 'RPR_X_normalized.csv'
  predictors: ['ndbi_mean', 'ntl_mean', 'ghi_mean', 'road_density_norm', 'poi_norm']
  target: 'num_bss'
  id_field: 'id'
  coord_cols: ['Longitude', 'Latitude']
  bbox_cols: ['left', 'bottom', 'right', 'top']

# Feature Engineering parameters
feature:
  scaling: 'minmax' # Options: 'minmax', 'standard', 'none'
  contiguity: 'queen' # Options: 'knn', 'queen', 'rook'
  n_neighbors: 8 # Used if contiguity is 'knn'
  imputer: 'median' # Options: 'mean', 'median', 'mode', 'drop', 'none'

# Training parameters
training:
  scv_method: 'kfold' # Options: 'kfold', 'stratified', 'group'
  scv_folds: 3
  n_samples: 1000      # MCMC samples
  n_tune: 1000         # Tuning samples
  n_chains: 2          # Number of chains
  target_accept: 0.9   # Target acceptance rate

# Model parameters
model:
  name: 'SEM_v1'
  kind: 'inference'
  link: 'logit'
  threshold: 0.5
  scale: True
  lag_order: 1
  beta_prior_std: 2.0      # Prior std for coefficients
  lambda_prior_std: 0.5    # Prior std for spatial parameter
  sigma_prior: 1.0         # Prior for error term

# Output parameters
output:
  outdir: 'out'
  model: 'trained_model.pkl'
  coefficients: 'model_coefficients.csv'
  weights: 'spatial_weights.pkl'
  report: 'evaluation_report.txt'
  predictions: 'predictions.csv'

# Logging and checkpoints
logging:
  logdir: 'logs'
  logpath: 'training.log'
  level: 'info'